# Generated by Django 6.0.3 on 2026-03-09 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contenu', models.CharField(choices=[('cours', 'Cours'), ('lecon', 'Leçon'), ('projet', 'Projet'), ('commentaire', 'Commentaire'), ('sujet_forum', 'Sujet du forum'), ('reponse_forum', 'Réponse du forum')], max_length=20)),
                ('id_contenu', models.IntegerField(help_text="ID de l'objet signalé")),
                ('raison', models.CharField(choices=[('fausse_info', 'Fausse information'), ('spam', 'Spam'), ('hors_sujet', 'Hors sujet'), ('inapproprie', 'Contenu inapproprié'), ('plagiat', 'Plagiat'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité'), ('ignore', 'Ignoré')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('signaleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_faits', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-date_creation'],
            },
        ),
    ]
