services:
  - type: web
    name: devafrique
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
      python manage.py init_render
    startCommand: "gunicorn siteweb.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "dev-afrique.onrender.com,.onrender.com,localhost"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_QWCGJNnPr4Y6@ep-icy-sun-ah25tfea-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://dev-afrique.onrender.com"
      - key: ADMIN_USERNAME
        value: "admin"
      - key: ADMIN_PASSWORD
        value: "DevAfrique2026!"
      - key: ADMIN_EMAIL
        value: "admin@devafrique.com"
      - key: PYTHON_VERSION
        value: "3.12.0"
