# Generated by Django 6.0.3 on 2026-03-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermeGlossaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terme', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('definition', models.TextField(help_text='Définition claire et simple')),
                ('exemple_code', models.TextField(blank=True, default='', help_text='Exemple de code (optionnel)')),
                ('langage_exemple', models.CharField(blank=True, default='', help_text="Langage de l'exemple", max_length=50)),
                ('categorie', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('mobile', 'Mobile'), ('base_donnees', 'Base de données'), ('devops', 'DevOps'), ('design', 'Design'), ('general', 'Général'), ('securite', 'Sécurité'), ('ia', 'Intelligence Artificielle')], default='general', max_length=20)),
                ('lettre', models.CharField(blank=True, max_length=1)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Terme du glossaire',
                'verbose_name_plural': 'Termes du glossaire',
                'ordering': ['terme'],
            },
        ),
    ]
