# Generated by Django 6.0.3 on 2026-03-09 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SujetForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('contenu', models.TextField()),
                ('categorie', models.CharField(choices=[('html_css', 'HTML & CSS'), ('javascript', 'JavaScript'), ('python', 'Python'), ('django', 'Django'), ('react', 'React'), ('mobile', 'Mobile'), ('devops', 'DevOps'), ('general', 'Général'), ('projets', 'Aide projets'), ('emploi', 'Emploi & Carrière')], default='general', max_length=20)),
                ('est_resolu', models.BooleanField(default=False)),
                ('est_epingle', models.BooleanField(default=False)),
                ('nb_vues', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets_forum', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sujet du forum',
                'verbose_name_plural': 'Sujets du forum',
                'ordering': ['-est_epingle', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ReponseForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('est_solution', models.BooleanField(default=False)),
                ('nb_votes', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_forum', to=settings.AUTH_USER_MODEL)),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='forum.sujetforum')),
            ],
            options={
                'verbose_name': 'Réponse du forum',
                'verbose_name_plural': 'Réponses du forum',
                'ordering': ['-est_solution', '-nb_votes', 'date_creation'],
            },
        ),
    ]
