# Generated by Django 6.0.3 on 2026-03-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPBloquee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_ip', models.GenericIPAddressField(db_index=True, unique=True)),
                ('raison', models.CharField(choices=[('brute_force', 'Tentatives de brute force'), ('injection', "Tentative d'injection SQL/XSS"), ('scan', 'Scan de vulnérabilités'), ('spam', 'Spam'), ('manuelle', 'Blocage manuel'), ('admin_brute', 'Brute force admin')], max_length=30)),
                ('details', models.TextField(blank=True, default='')),
                ('date_blocage', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, help_text='Laisser vide pour un blocage permanent', null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('nombre_tentatives', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'IP bloquée',
                'verbose_name_plural': 'IPs bloquées',
                'ordering': ['-date_blocage'],
            },
        ),
        migrations.CreateModel(
            name='JournalSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('login_echoue', 'Connexion échouée'), ('brute_force', 'Brute force détecté'), ('ip_bloquee', 'IP bloquée'), ('injection', "Tentative d'injection"), ('acces_interdit', 'Accès interdit'), ('scan', 'Scan détecté'), ('admin_bloque', 'Admin bloqué'), ('fichier_suspect', 'Fichier suspect'), ('autre', 'Autre')], max_length=30)),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('danger', 'Danger'), ('critique', 'Critique')], default='info', max_length=10)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('nom_utilisateur', models.CharField(blank=True, default='', max_length=150)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('description', models.TextField()),
                ('donnees', models.JSONField(blank=True, default=dict)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Journal de sécurité',
                'verbose_name_plural': 'Journaux de sécurité',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TentativeAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_ip', models.GenericIPAddressField(db_index=True)),
                ('nom_utilisateur', models.CharField(max_length=150)),
                ('reussie', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Tentative admin',
                'verbose_name_plural': 'Tentatives admin',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TentativeConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_ip', models.GenericIPAddressField(db_index=True)),
                ('nom_utilisateur', models.CharField(blank=True, default='', max_length=150)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('reussie', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('localisation', models.CharField(blank=True, default='', max_length=255)),
                ('referer', models.URLField(blank=True, default='')),
                ('chemin', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Tentative de connexion',
                'verbose_name_plural': 'Tentatives de connexion',
                'ordering': ['-date'],
            },
        ),
    ]
