# Generated by Django 6.0.3 on 2026-03-10 00:40

import utilisateurs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_utilisateur_niveau_utilisateur_pays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Photo de profil (JPG, PNG, max 2 Mo)', null=True, upload_to=utilisateurs.models.chemin_avatar),
        ),
    ]
