# Generated by Django 6.0.3 on 2026-03-09 23:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_initial'),
        ('projets', '0003_projetcommunautaire_nb_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cours',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cours',
            name='nb_vues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cours',
            name='niveau',
            field=models.CharField(choices=[('debutant', '🌱 Débutant'), ('intermediaire', '🌿 Intermédiaire'), ('avance', '🌳 Avancé')], default='debutant', max_length=20),
        ),
        migrations.AddField(
            model_name='cours',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('publie', 'Publié'), ('refuse', 'Refusé')], default='publie', max_length=20),
        ),
        migrations.AddField(
            model_name='lecon',
            name='duree_minutes',
            field=models.IntegerField(default=10, help_text='Durée estimée en minutes'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='type_parcours',
            field=models.CharField(choices=[('web', 'Développement Web'), ('mobile', 'Développement Mobile'), ('data', 'Data & IA'), ('devops', 'DevOps & Cloud'), ('design', 'Design & UI/UX'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL)),
                ('lecon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='cours.lecon')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='cours.commentaire')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='projets.projetcommunautaire')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_unique', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('date_obtention', models.DateTimeField(auto_now_add=True)),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.parcours')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
                'unique_together': {('utilisateur', 'parcours')},
            },
        ),
    ]
