# Generated by Django 6.0.3 on 2026-03-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetCommunautaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('technologies', models.CharField(help_text='Technologies séparées par des virgules', max_length=500)),
                ('lien_projet', models.URLField(blank=True, default='')),
                ('lien_github', models.URLField(blank=True, default='')),
                ('capture_url', models.URLField(blank=True, default='', help_text="URL de la capture d'écran")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projet communautaire',
                'verbose_name_plural': 'Projets communautaires',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
